- name: show secrets
  hosts: servers
  become: yes
  vars_files: 
   - secrets.txt
  tasks:
   - name: show password
     debug:
      msg: "my password is {{ password }}"
     no_log: true
   - name: show api_key
     debug: 
      msg: "my api key is  {{ api_key }}"
     no_log: true
